"""Write audio/mix.json: the bed, one keyclick per typed character, and the accents.

Key times follow the typewriter component's uniform cadence exactly (1/cps per character,
+0.12 s after a space), so each click lands on the frame its character appears.
"""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
T0 = 17.4  # terminal scene start (index.html)
CMDS = [(0.45, "pip install black==26.1.0"), (2.45, "black --check app.py"), (4.35, "black app.py")]
CPS, WORD_GAP = 22, 0.12

DUCK_KEYS = ["glitch"] + [f"key{i}" for i in range(57)] + ["ret25", "ret45", "ret57"]
tracks = [
    {"id": "bed", "kind": "music", "compose": {"style": "deep-house", "bpm": 122, "key": "Am",
     "sections": "0:intro,3.6:verse,10.2:build,17.4:break,24.6:drop,30.2:outro", "seed": 3},
     "gain_db": 0, "fade_out": 0.8,
     "section_gain": {"intro": 2, "break": 4},
     "duck": {"under": DUCK_KEYS, "depth_db": 3, "attack": 0.02, "release": 0.35, "hold": 0.1}},
    # the bug beat: the glitch cut into diff-2 (glitch transition swaps at the scene start)
    {"id": "glitch", "kind": "sfx", "file": "audio/glitch.wav", "at": 10.2 - 0.1, "align": "start", "gain_db": -1},
    # each diff applies: a soft knock as the removed lines turn red and the added lines open
    # (index.html: diff-1 diffAt 2.5; diff-2 panel a diffAt 1.5, panel b diffAt 3.3)
    {"kind": "sfx", "file": "audio/thock.wav", "at": 3.6 + 2.5, "align": "hit", "gain_db": -6},
    {"kind": "sfx", "file": "audio/thock.wav", "at": 10.2 + 1.5, "align": "hit", "gain_db": -6},
    {"kind": "sfx", "file": "audio/thock.wav", "at": 10.2 + 3.3, "align": "hit", "gain_db": -6},
    # "Oh no! ... 1 file would be reformatted." lands (terminal --d 3.8s): a softer knock, which
    # also covers the bar-end gap in the composed break (bed near-silent ~21.0-21.6 s)
    {"kind": "sfx", "file": "audio/thock.wav", "at": 17.4 + 3.8, "align": "hit", "gain_db": -8},
]
n = 0
for at, text in CMDS:
    t = T0 + at
    for ch in text:
        t += 1 / CPS
        if ch == " ":
            t += WORD_GAP
        tracks.append({"id": f"key{n}", "kind": "sfx", "file": f"audio/key-{n % 4 + 1}.wav", "at": round(t, 4), "align": "hit",
                       "gain_db": 4 if ch != " " else 5, "pan": round(((n * 37) % 11 - 5) / 25, 2)})
        n += 1
    # the Return key after each command
    tracks.append({"id": f"ret{n}", "kind": "sfx", "file": "audio/key-1.wav", "at": round(t + 0.12, 4), "align": "hit", "gain_db": 6})

mix = {"_comment": "Generated by tools/keyclicks.py; edit that file, not this one.", "duration": 35.0,
       "sample_rate": 48000, "tracks": tracks, "master": {"lufs": -14, "true_peak": -1}}
(ROOT / "audio" / "mix.json").write_text(json.dumps(mix, indent=1) + "\n")
print(f"{n} key clicks, {len(tracks)} tracks")
