/* Every on-screen string, in English and French, plus the narration words each reveal waits for.
 * lang.js sets LANG. Facts: research/13-facts.md (F-ids). Licensed CC BY-SA 4.0 like the script. */
'use strict';

var STRINGS = {
  en: {
    // hook
    kicker: 'REAL FOOTAGE',
    title: 'The waggle dance',
    hookSub: 'A forager tells her nestmates where food is.',
    traceLabel: 'Her red paint mark, tracked',
    traceNote: '(the camera moves with her)',
    footCap: 'A marked forager dancing for a feeder 200 m away',
    footCredit: 'Su et al. 2008, PLOS ONE · CC BY 3.0',
    // problem
    outside: 'OUTSIDE',
    inside: 'INSIDE THE HIVE',
    dark: 'dark',
    vertical: 'a vertical wall',
    noPoint: 'no line of sight',
    // angle
    topView: 'OUTSIDE · SEEN FROM ABOVE',
    combView: 'INSIDE · ON THE VERTICAL COMB',
    sun: 'sun',
    food: 'food',
    hive: 'hive',
    up: 'up',
    upIsSun: 'straight up = toward the sun',
    run: 'waggle run',
    sunMoves: 'the sun moves',
    // distance
    loopLeft: 'turn left',
    loopRight: 'turn right',
    returnLbl: 'return',
    fig8: 'a figure-eight',
    near: 'NEAR FOOD',
    far: 'FAR FOOD',
    waggleTime: 'waggle time',
    fartherLonger: 'Farther food, longer waggle',
    // round
    species: 'Italian honey bee',
    speciesLatin: 'Apis mellifera ligustica',
    roundDance: 'round dance',
    transitional: 'transitional',
    waggleDance: 'waggle dance',
    zRound: '~10 m',
    zTrans: '20–30 m',
    zWaggle: '> 40 m',
    distFromHive: 'distance from the hive',
    // source
    srcKicker: 'SOURCE',
    srcLine: 'English Wikipedia, rev\u00a01371912261',
    vfName: 'Karl von Frisch',
    vfRole: 'Austrian ethologist',
    vfNobel: 'Nobel Prize, 1973\u00a0(shared)',
    vfFirst: 'one of the first to decode the dance',
    url: 'en.wikipedia.org/wiki/Waggle_dance',
    // credit
    payoffA: 'Angle tells direction.',
    payoffB: 'Duration tells distance.',
    credit1: 'Adapted from Wikipedia, “Waggle dance” (rev 1371912261), CC BY-SA 4.0 · summarised and animated',
    credit2: 'Bee footage: Su et al. 2008, PLOS ONE, CC BY 3.0',
    credit3: 'This video is licensed CC BY-SA 4.0',
    credit4: 'Voice: Kokoro-82M (af_heart), Apache-2.0 · Music: composed in code for this film',
    // narration words that trigger reveals (first match in that line, or [word, nth])
    w: {
      dark: 'dark', vertical: 'vertical', point: 'point', dances: 'dances',
      comb: 'comb', up: 'up', sun: 'sun', food: 'food', deg1: ['forty-five', 0], waggle: 'waggle', deg2: ['forty-five', 1],
      sunMoves: 'moves', shifts: 'shifts',
      left: 'left', right: 'right', fig8: 'figure-eight', distance: 'distance', farther: 'farther', longer: 'longer',
      close: 'close', ten: 'ten', circle: 'circle', forty: 'forty', stretches: 'stretches',
      frisch: 'Frisch', nobel: 'Nobel', first: 'first',
    },
  },
  fr: {
    kicker: 'IMAGES RÉELLES',
    title: 'La danse frétillante',
    hookSub: 'Une butineuse indique à ses compagnes où trouver de la nourriture.',
    traceLabel: 'Sa marque de peinture rouge, suivie',
    traceNote: '(la caméra la suit)',
    footCap: 'Une butineuse marquée danse pour une mangeoire à 200 m',
    footCredit: 'Su et al. 2008, PLOS ONE · CC BY 3.0',
    outside: 'DEHORS',
    inside: 'DANS LA RUCHE',
    dark: 'noir',
    vertical: 'un mur vertical',
    noPoint: 'hors de vue',
    topView: 'DEHORS · VU DU DESSUS',
    combView: 'DEDANS · SUR LE RAYON VERTICAL',
    sun: 'soleil',
    food: 'nourriture',
    hive: 'ruche',
    up: 'haut',
    upIsSun: 'vers le haut = vers le soleil',
    run: 'course frétillante',
    sunMoves: 'le soleil se déplace',
    loopLeft: 'à gauche',
    loopRight: 'à droite',
    returnLbl: 'retour',
    fig8: 'un huit',
    near: 'NOURRITURE PROCHE',
    far: 'NOURRITURE LOINTAINE',
    waggleTime: 'durée du frétillement',
    fartherLonger: 'Plus c’est loin, plus elle frétille',
    species: 'Abeille italienne',
    speciesLatin: 'Apis mellifera ligustica',
    roundDance: 'danse en rond',
    transitional: 'transition',
    waggleDance: 'danse frétillante',
    zRound: '~10 m',
    zTrans: '20–30 m',
    zWaggle: '> 40 m',
    distFromHive: 'distance à la ruche',
    srcKicker: 'SOURCE',
    srcLine: 'Wikipédia en anglais, rév.\u00a01371912261',
    vfName: 'Karl von Frisch',
    vfRole: 'éthologue autrichien',
    vfNobel: 'prix Nobel 1973\u00a0(partagé)',
    vfFirst: 'l’un des premiers à la déchiffrer',
    url: 'en.wikipedia.org/wiki/Waggle_dance',
    payoffA: 'L’angle donne la direction.',
    payoffB: 'La durée donne la distance.',
    credit1: 'Adapté de Wikipédia (en anglais), « Waggle dance » (rév. 1371912261), CC BY-SA 4.0 · résumé, traduit et animé',
    credit2: 'Images d’abeilles : Su et al. 2008, PLOS ONE, CC BY 3.0',
    credit3: 'Cette vidéo est sous licence CC BY-SA 4.0',
    credit4: 'Voix : Kokoro-82M (ff_siwis), Apache-2.0 · Musique : composée en code pour ce film',
    w: {
      dark: 'noir', vertical: 'vertical', point: 'montrer', dances: 'danse',
      comb: 'rayon', up: 'haut', sun: 'soleil', food: 'nourriture', deg1: ['quarante-cinq', 0], waggle: 'course', deg2: ['quarante-cinq', 1],
      sunMoves: 'déplace', shifts: 'ajuste',
      left: 'gauche', right: 'droite', fig8: 'huit', distance: 'distance', farther: 'loin', longer: 'longtemps',
      close: 'près', ten: 'dizaine', circle: 'rond', forty: 'quarante', stretches: 'étire',
      frisch: 'Frisch', nobel: 'Nobel', first: 'premiers',
    },
  },
};

var S = STRINGS[typeof LANG === 'string' ? LANG : 'en'];
